# Generated by Django 2.2 on 2019-04-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchasechildmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasechildmodel',
            name='type',
        ),
    ]
