# Generated by Django 2.2 on 2019-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_supplier', '0002_supplieraddress_suppliereducation_suppliermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='supplier_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
