# Generated by Django 2.2 on 2019-04-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.IntegerField(unique=True)),
                ('product_cost_price', models.PositiveIntegerField()),
                ('product_mrp', models.PositiveIntegerField()),
                ('product_tax', models.FloatField(max_length=50)),
                ('product_unit', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('open_stock', models.PositiveIntegerField()),
                ('product_status', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(max_length=5)),
                ('cover_image', models.ImageField(default='company/blank.png', upload_to='product_template/cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplateSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubCategory')),
                ('product_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_template.ProductTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplateImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_title', models.CharField(max_length=100)),
                ('product_image', models.ImageField(default='company/blank.png', upload_to='product_template/other/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_template.ProductTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('product_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_template.ProductTemplate')),
            ],
        ),
    ]
