# Generated by Django 2.2 on 2019-04-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttemplatecategory',
            old_name='product_template_id',
            new_name='product_template',
        ),
        migrations.RenameField(
            model_name='producttemplatesubcategory',
            old_name='product_template_id',
            new_name='product_template',
        ),
    ]
