# Generated by Django 2.2 on 2019-04-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_template', '0002_auto_20190413_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttemplateimages',
            old_name='product_template_id',
            new_name='product_template',
        ),
    ]
