# Generated by Django 2.2 on 2019-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_template', '0004_remove_producttemplate_open_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='product_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
